### ISSUE TITLE
TypeError: _.trunc is not a function

### ISSUE THREAD

**Issue by zr53** [macacajs/webdriver-server#44]
```
TypeError: _.trunc is not a function
      at Object.module.exports (D:\Work\AppRepeater\AutoTest\node_modules\_webdriver-server@1.0.77@webdriver-server\lib\server\responseHandler.js:45:23)
      at module.exports.next (<anonymous>)
      at onFulfilled (D:\Work\AppRepeater\AutoTest\node_modules\_co@4.6.0@co\index.js:65:19)
      at <anonymous>
```
Reason:　`trunc()` in lodash Version 3 was renamed to `truncate()` in Version 4
https://github.com/lodash/lodash/issues/1930

**Comment by xudafeng** [comment]
https://github.com/macacajs/webdriver-server/commit/2edb44119e8b47b03d5a6b4efe7c54d71436f839
